### ISSUE TITLE
Get to 100% test coverage

### ISSUE THREAD

**Issue by adamtheturtle** [VWS-Python/vws-python-mock#1831]
Not covered:

- [X] `RandomTargetTrackingRater.call` # (Done in #1900)
- [X] `TargetTrackingRater.call` # (Done in #1900)
- [X] `ImageMatcher.call` # (Done in #1900)
- [X] `--skip_docker_build_tests` (done in #1841)
- `TERMINATE_WSGI_INPUT` options
- `make_image_file` branch for `"L"`

Also change Codecov settings to fail on <100% coverage.
